import type { FashionAssociation } from "@/src/knowledge/genreFashionMap";

export const eraFashionAssociations: FashionAssociation[] = [
  { id: "1970s-rock-folk", genres: ["rock", "folk", "blues", "classic rock", "blues rock", "folk rock", "soft rock"], eras: ["1970s", "1960s"], signals: { colors: ["camel", "rust", "cream", "denim", "forest green", "tobacco"], materials: ["suede", "denim", "crochet", "rib knit", "brown leather"], silhouettes: ["flared", "relaxed", "fitted"], garmentTypes: ["bell bottoms", "crochet top", "fitted knit top", "suede jacket", "vintage boots", "leather belt", "beaded necklace"], accessories: ["leather belt", "beaded necklace", "silk scarf"], aesthetics: ["bohemian", "vintage", "worn-in", "earthy"] }, weight: 1.45 },
  { id: "2000s-pop-rock", genres: ["pop rock", "alternative rock", "rock"], eras: ["2000s"], signals: { colors: ["black", "burgundy", "washed black", "silver"], materials: ["distressed denim", "rib knit", "leather", "mesh"], silhouettes: ["fitted", "low-slung", "layered"], garmentTypes: ["distressed fitted graphic tee", "low-rise jeans", "corset-detail top", "cropped leather jacket", "combat boots"], accessories: ["compact shoulder bag", "studded belt"], aesthetics: ["nostalgic", "mall-punk"] }, weight: 1.15 },
  { id: "1990s-rnb", genres: ["r&b", "contemporary r&b"], eras: ["1990s"], signals: { colors: ["black", "white", "gold", "burgundy"], materials: ["rib knit", "satin", "denim"], silhouettes: ["fitted", "straight"], garmentTypes: ["slip skirt", "rib knit long sleeve", "gold hoops"], aesthetics: ["sleek", "minimal"] }, weight: 1.05 },
  { id: "2010s-indie", genres: ["indie folk", "indie"], eras: ["2010s"], signals: { colors: ["earth green", "cream", "denim"], materials: ["linen", "washed denim", "knit"], silhouettes: ["relaxed", "layered"], garmentTypes: ["cropped denim jacket", "scarf", "sneakers"], aesthetics: ["casual", "tactile"] }, weight: 1 },
  { id: "1980s-pop-dance", genres: ["pop", "dance pop", "funk", "disco", "soul", "r&b"], eras: ["1980s"], signals: { colors: ["black", "chocolate", "plum", "cream", "gold"], materials: ["satin", "leather", "metallic", "sequin", "rib knit"], silhouettes: ["sharp", "fitted", "flared", "tailored"], garmentTypes: ["satin cowl top", "sequin top", "fitted leather jacket", "statement flared trouser", "detailed tailored trouser", "pointed leather boots", "distinctive loafers", "sculptural gold earrings"], accessories: ["sculptural gold earrings", "statement belt"], aesthetics: ["nightlife", "vintage", "retro", "glossy", "dramatic"] }, weight: 1.3 },
  { id: "1990s-alt-rock", genres: ["alternative rock", "rock", "grunge", "shoegaze", "riot-grrrl"], eras: ["1990s"], signals: { colors: ["washed denim", "charcoal", "cream", "burgundy", "faded olive"], materials: ["washed denim", "flannel", "cotton", "fuzzy knit", "distressed denim"], silhouettes: ["slouchy", "layered", "relaxed"], garmentTypes: ["flannel shirt", "faded tee", "baggy jeans", "slip dress", "cardigan", "combat boots", "worn sneakers"], accessories: ["skinny scarf", "beanie"], aesthetics: ["worn-in", "distressed", "grunge"] }, weight: 1.34 },
  { id: "2000s-post-grunge-alt", genres: ["post-grunge", "alternative rock", "modern rock", "pop rock"], eras: ["2000s"], signals: { colors: ["black", "washed black", "charcoal", "burgundy", "dirty white"], materials: ["distressed denim", "rib knit", "leather", "thermal knit"], silhouettes: ["layered", "low-slung", "fitted", "slightly oversized"], garmentTypes: ["thermal top", "distressed fitted graphic tee", "low-rise jeans", "leather trousers", "combat boots", "moto boots", "compact shoulder bag"], accessories: ["studded belt", "skinny scarf"], aesthetics: ["mall-punk", "distressed", "lived-in"] }, weight: 1.28 },
  { id: "2000s-rnb-pop", genres: ["r&b", "pop", "dance pop"], eras: ["2000s"], signals: { colors: ["white", "black", "gold", "hot pink", "silver"], materials: ["rib knit", "satin", "mesh", "denim"], silhouettes: ["body-skimming", "cropped", "low-slung"], garmentTypes: ["corset top", "low-rise jeans", "mini bag", "platform heels", "kitten heels"], accessories: ["gold hoops", "charm necklace"], aesthetics: ["sleek", "nostalgic"] }, weight: 1.1 },
  { id: "2020s-pop-digital", genres: ["pop", "electropop", "hyperpop", "rap"], eras: ["2020s"], signals: { colors: ["black", "silver", "electric blue", "hot pink"], materials: ["mesh", "patent", "nylon", "metallic"], silhouettes: ["cropped", "oversized", "asymmetric"], garmentTypes: ["asymmetric top", "cargo pants", "ballet sneakers", "crescent bag"], accessories: ["sunglasses"], aesthetics: ["digital", "street"] }, weight: 1 },
  { id: "2020s-editorial", eras: ["2020s"], signals: { colors: ["burgundy", "royal purple", "butter yellow", "electric blue"], materials: ["satin", "suede", "leather"], silhouettes: ["tailored", "asymmetric", "relaxed"], garmentTypes: ["short jacket", "asymmetric skirt", "ballet flats", "tote bag"], accessories: ["pendant necklace"], aesthetics: ["current", "polished"] }, weight: 0.58 },
];
