import type { FashionAssociation } from "@/src/knowledge/genreFashionMap";

export const eraFashionAssociations: FashionAssociation[] = [
  { id: "1970s-rock-folk", genres: ["rock", "folk", "blues"], eras: ["1970s"], signals: { colors: ["camel", "rust", "cream", "denim"], materials: ["suede", "denim", "cotton"], silhouettes: ["flared", "relaxed"], garmentTypes: ["wide-leg trouser", "clogs", "scarf"], aesthetics: ["bohemian", "worn-in"] }, weight: 1.1 },
  { id: "2000s-pop-rock", genres: ["pop rock", "alternative rock", "rock"], eras: ["2000s"], signals: { colors: ["black", "burgundy", "denim", "silver"], materials: ["washed denim", "rib knit", "leather"], silhouettes: ["fitted", "low-slung", "layered"], garmentTypes: ["graphic baby tee", "low-rise jeans", "zip hoodie", "layered tank", "compact shoulder bag"], accessories: ["compact shoulder bag", "studded belt"], aesthetics: ["nostalgic", "mall-punk"] }, weight: 1.15 },
  { id: "1990s-rnb", genres: ["r&b", "contemporary r&b"], eras: ["1990s"], signals: { colors: ["black", "white", "gold", "burgundy"], materials: ["rib knit", "satin", "denim"], silhouettes: ["fitted", "straight"], garmentTypes: ["slip skirt", "rib knit long sleeve", "gold hoops"], aesthetics: ["sleek", "minimal"] }, weight: 1.05 },
  { id: "2010s-indie", genres: ["indie folk", "indie"], eras: ["2010s"], signals: { colors: ["earth green", "cream", "denim"], materials: ["linen", "washed denim", "knit"], silhouettes: ["relaxed", "layered"], garmentTypes: ["cropped denim jacket", "scarf", "sneakers"], aesthetics: ["casual", "tactile"] }, weight: 1 },
  { id: "1980s-pop-dance", genres: ["pop", "dance pop", "funk", "disco"], eras: ["1980s"], signals: { colors: ["black", "white", "gold", "electric blue", "vibrant red"], materials: ["satin", "leather", "metallic"], silhouettes: ["structured", "fitted"], garmentTypes: ["fitted blazer", "bodycon dress", "kitten heels", "statement jewelry"], accessories: ["statement jewelry"], aesthetics: ["glossy", "bold"] }, weight: 1.05 },
  { id: "1990s-alt-rock", genres: ["alternative rock", "rock", "grunge"], eras: ["1990s"], signals: { colors: ["black", "denim", "burgundy", "cream"], materials: ["washed denim", "cotton", "leather"], silhouettes: ["slouchy", "layered"], garmentTypes: ["baggy jeans", "graphic baby tee", "boots", "trench coat"], accessories: ["skinny scarf"], aesthetics: ["worn-in", "distressed"] }, weight: 1.08 },
  { id: "2000s-rnb-pop", genres: ["r&b", "pop", "dance pop"], eras: ["2000s"], signals: { colors: ["white", "black", "gold", "hot pink", "silver"], materials: ["rib knit", "satin", "mesh", "denim"], silhouettes: ["body-skimming", "cropped", "low-slung"], garmentTypes: ["corset top", "low-rise jeans", "mini bag", "kitten heels"], accessories: ["gold hoops", "charm necklace"], aesthetics: ["sleek", "nostalgic"] }, weight: 1.1 },
  { id: "2020s-pop-digital", genres: ["pop", "electropop", "hyperpop", "rap"], eras: ["2020s"], signals: { colors: ["black", "silver", "electric blue", "hot pink"], materials: ["mesh", "patent", "nylon", "metallic"], silhouettes: ["cropped", "oversized", "asymmetric"], garmentTypes: ["asymmetric top", "cargo pants", "ballet sneakers", "crescent bag"], accessories: ["sunglasses"], aesthetics: ["digital", "street"] }, weight: 1 },
  { id: "2020s-editorial", eras: ["2020s"], signals: { colors: ["burgundy", "royal purple", "butter yellow", "electric blue"], materials: ["satin", "suede", "leather"], silhouettes: ["tailored", "asymmetric", "relaxed"], garmentTypes: ["short jacket", "asymmetric skirt", "ballet flats", "tote bag"], accessories: ["pendant necklace"], aesthetics: ["current", "polished"] }, weight: 0.58 },
];
