import type { GarmentCategory } from "@/src/domain/style/types";

export const CATEGORY_LIMITS: Partial<Record<GarmentCategory, number>> = {
  top: 1,
  bottom: 1,
  dress: 1,
  outerwear: 1,
  shoes: 1,
  bag: 1,
  jewelry: 2,
  accessory: 2,
};

export const GARMENT_CATEGORY: Record<string, GarmentCategory> = {
  "moto jacket": "outerwear",
  "cropped moto jacket": "outerwear",
  "cropped leather jacket": "outerwear",
  "fitted leather jacket": "outerwear",
  "distressed leather jacket": "outerwear",
  "worn leather moto jacket": "outerwear",
  "fitted moto jacket": "outerwear",
  "military-inspired jacket": "outerwear",
  "cropped denim jacket": "outerwear",
  "rhinestone denim jacket": "outerwear",
  "zip hoodie": "outerwear",
  "faux fur jacket": "outerwear",
  "cropped faux fur jacket": "outerwear",
  "suede jacket": "outerwear",
  "oversized blazer": "outerwear",
  "trench coat": "outerwear",
  "track jacket": "outerwear",
  "short jacket": "outerwear",
  "fitted blazer": "outerwear",
  cardigan: "outerwear",
  "bomber jacket": "outerwear",
  "cropped bomber jacket": "outerwear",
  "barn jacket": "outerwear",
  "leather blazer": "outerwear",
  "puffer jacket": "outerwear",
  "utility jacket": "outerwear",
  "fleece jacket": "outerwear",
  "shawl cardigan": "outerwear",
  "field jacket": "outerwear",
  "anorak": "outerwear",
  "duster coat": "outerwear",
  "peacoat": "outerwear",
  "varsity jacket": "outerwear",
  "windbreaker": "outerwear",
  "fur-trim coat": "outerwear",
  "cape coat": "outerwear",
  "vest": "outerwear",
  "leather trench": "outerwear",
  "graphic baby tee": "top",
  "rib knit long sleeve": "top",
  "layered tank": "top",
  "layered camisole": "top",
  "lace camisole": "top",
  "lace ruffle cami": "top",
  "double-layer tank": "top",
  "leather tank top": "top",
  "mesh tank top": "top",
  "silk cami": "top",
  "soft camisole": "top",
  "corset top": "top",
  "mesh long sleeve": "top",
  "button-up shirt": "top",
  "football jersey": "top",
  "halter top": "top",
  "asymmetric top": "top",
  "asymmetric fitted top": "top",
  "cowl top": "top",
  "draped top": "top",
  "satin cowl top": "top",
  "corset-detail top": "top",
  "sheer printed top": "top",
  "burnout graphic top": "top",
  "distressed fitted graphic tee": "top",
  "peplum top": "top",
  "prairie blouse": "top",
  "flannel shirt": "top",
  "oversized knit": "top",
  "faded tee": "top",
  "fuzzy knit": "top",
  "white tee": "top",
  "tank top": "top",
  bodysuit: "top",
  "polo shirt": "top",
  "lace blouse": "top",
  "band tee": "top",
  "goth baby tee": "top",
  "y2k baby tee": "top",
  "tattoo graphic baby tee": "top",
  "cyber graphic baby tee": "top",
  sweatshirt: "top",
  "tube top": "top",
  "wrap top": "top",
  "turtleneck": "top",
  "crop top": "top",
  "rugby shirt": "top",
  "henley top": "top",
  "off-shoulder top": "top",
  "satin blouse": "top",
  "jersey top": "top",
  "tunic top": "top",
  "crochet top": "top",
  "linen top": "top",
  "fitted knit top": "top",
  "buttoned vest": "top",
  "sequin top": "top",
  "graphic hoodie": "top",
  "thermal top": "top",
  "mock neck top": "top",
  "low-rise jeans": "bottom",
  "slip skirt": "bottom",
  "wide-leg trouser": "bottom",
  "mini skirt": "bottom",
  "cargo pants": "bottom",
  "pleated skirt": "bottom",
  "baggy jeans": "bottom",
  "track pants": "bottom",
  "asymmetric skirt": "bottom",
  "capri pants": "bottom",
  "satin pants": "bottom",
  "statement flared trouser": "bottom",
  "detailed tailored trouser": "bottom",
  bloomers: "bottom",
  jorts: "bottom",
  "straight jeans": "bottom",
  "bootcut jeans": "bottom",
  "bell bottoms": "bottom",
  leggings: "bottom",
  "tailored trouser": "bottom",
  "pencil skirt": "bottom",
  "maxi skirt": "bottom",
  "flowy maxi skirt": "bottom",
  "denim skirt": "bottom",
  shorts: "bottom",
  "leather pants": "bottom",
  "leather trousers": "bottom",
  "leather flare trousers": "bottom",
  "leather mini skirt": "bottom",
  "studded mini skirt": "bottom",
  "plaid mini skirt": "bottom",
  "kilt mini": "bottom",
  "lace-trim mini": "bottom",
  "distressed statement pants": "bottom",
  "hardware low-rise trouser": "bottom",
  "parachute pants": "bottom",
  "bike shorts": "bottom",
  "micro skirt": "bottom",
  "wrap skirt": "bottom",
  "column skirt": "bottom",
  "utility skirt": "bottom",
  "pinstripe trouser": "bottom",
  "sweatpants": "bottom",
  "wide-leg lounge pants": "bottom",
  "flare jeans": "bottom",
  "lace skirt": "bottom",
  "slip dress": "dress",
  "lace slip dress": "dress",
  "washed slip dress": "dress",
  "distressed slip dress": "dress",
  "asymmetrical mini dress": "dress",
  "mesh dress": "dress",
  "lingerie-inspired dress": "dress",
  "bodycon dress": "dress",
  "prairie dress": "dress",
  "mini dress": "dress",
  "shirt dress": "dress",
  "sweater dress": "dress",
  "maxi dress": "dress",
  "lace dress": "dress",
  "corset dress": "dress",
  "wrap dress": "dress",
  "babydoll dress": "dress",
  "tube dress": "dress",
  "sequin dress": "dress",
  "denim dress": "dress",
  "column dress": "dress",
  "halter dress": "dress",
  "animal-print dress": "dress",
  "leopard mini dress": "dress",
  "cutout dress": "dress",
  catsuit: "dress",
  boots: "shoes",
  sneakers: "shoes",
  clogs: "shoes",
  loafers: "shoes",
  "ballet flats": "shoes",
  "kitten heels": "shoes",
  "platform sandals": "shoes",
  "platform heels": "shoes",
  oxfords: "shoes",
  "tall boots": "shoes",
  "ballet sneakers": "shoes",
  "boat shoes": "shoes",
  "mary janes": "shoes",
  "cowboy boots": "shoes",
  "vintage boots": "shoes",
  "hiking boots": "shoes",
  mules: "shoes",
  pumps: "shoes",
  "stiletto heels": "shoes",
  "strappy sandals": "shoes",
  "combat boots": "shoes",
  "worn sneakers": "shoes",
  "running sneakers": "shoes",
  "platform boots": "shoes",
  "knee-high boots": "shoes",
  "pointed leather boots": "shoes",
  "engineer boots": "shoes",
  "moto boots": "shoes",
  "hardware-heavy boots": "shoes",
  "slingback heels": "shoes",
  "wedge sandals": "shoes",
  "soccer sneakers": "shoes",
  "skate shoes": "shoes",
  "chunky sneakers": "shoes",
  "rain boots": "shoes",
  "espadrilles": "shoes",
  "pointed flats": "shoes",
  "distinctive loafers": "shoes",
  "compact shoulder bag": "bag",
  "crescent bag": "bag",
  "mini bag": "bag",
  "tote bag": "bag",
  "flap bag": "bag",
  "croc-effect bag": "bag",
  "embellished shoulder bag": "bag",
  clutch: "bag",
  "crossbody bag": "bag",
  "bucket bag": "bag",
  backpack: "bag",
  "hobo bag": "bag",
  "top-handle bag": "bag",
  "slouchy tote": "bag",
  "saddle bag": "bag",
  "belt bag": "bag",
  "wristlet": "bag",
  "bowler bag": "bag",
  "barrel bag": "bag",
  "beaded bag": "bag",
  "suede shoulder bag": "bag",
  "metallic clutch": "bag",
  "unusual leather bag": "bag",
  "hardware shoulder bag": "bag",
  "slouchy leather bag": "bag",
  "gold hoops": "jewelry",
  "gold jewelry": "jewelry",
  "silver jewelry": "jewelry",
  "statement jewelry": "jewelry",
  "sculptural gold earrings": "jewelry",
  "pearl jewelry": "jewelry",
  "charm necklace": "jewelry",
  "pendant necklace": "jewelry",
  brooch: "jewelry",
  "shell earrings": "jewelry",
  "chain necklace": "jewelry",
  "silver pendant": "jewelry",
  "layered silver necklaces": "jewelry",
  "signet ring": "jewelry",
  "cuff bracelet": "jewelry",
  choker: "jewelry",
  "beaded necklace": "jewelry",
  "drop earrings": "jewelry",
  "ear cuff": "jewelry",
  "locket necklace": "jewelry",
  "tennis bracelet": "jewelry",
  "stacking rings": "jewelry",
  "statement rings": "jewelry",
  "body chain": "jewelry",
  "watch": "jewelry",
  "bangle bracelet": "jewelry",
  hardware: "accessory",
  scarf: "accessory",
  "patterned scarf": "accessory",
  "studded belt": "accessory",
  "grommet belt": "accessory",
  "statement belt": "accessory",
  "leather belt": "accessory",
  "baseball cap": "accessory",
  "skinny scarf": "accessory",
  "hair clips": "accessory",
  "sunglasses": "accessory",
  beanie: "accessory",
  beret: "accessory",
  "silk scarf": "accessory",
  "waist belt": "accessory",
  "phone charm": "accessory",
  "leg warmers": "accessory",
  "knee socks": "accessory",
  "fishnet tights": "accessory",
  "patterned tights": "accessory",
  "arm warmers": "accessory",
  "headband": "accessory",
  "scrunchie": "accessory",
  "necktie": "accessory",
  "bandana": "accessory",
  "mesh gloves": "accessory",
  "chain belt": "accessory",
  "corsage": "accessory",
  "experimental accessory": "accessory",
};
