export type FashionAssociation = {
  id: string;
  genres?: string[];
  eras?: string[];
  scenes?: string[];
  signals: {
    traits?: string[];
    colors?: string[];
    materials?: string[];
    silhouettes?: string[];
    garmentTypes?: string[];
    accessories?: string[];
    aesthetics?: string[];
  };
  weight: number;
};

export const genreFashionAssociations: FashionAssociation[] = [
  { id: "punk-general", genres: ["punk"], signals: { traits: ["rebellious"], colors: ["black", "burgundy"], materials: ["leather", "distressed denim"], silhouettes: ["structured", "slightly oversized"], garmentTypes: ["moto jacket", "boots", "studded belt"], accessories: ["hardware"], aesthetics: ["rebellious", "distressed"] }, weight: 1 },
  { id: "neo-soul-general", genres: ["neo-soul", "soul"], signals: { traits: ["earthy", "textural"], colors: ["earth green", "cream", "chocolate", "gold"], materials: ["knit", "suede", "linen"], silhouettes: ["draped", "relaxed"], garmentTypes: ["scarf", "wide-leg trouser"], accessories: ["patterned scarf", "gold jewelry"], aesthetics: ["warm", "artful"] }, weight: 1 },
  { id: "rnb-general", genres: ["r&b", "contemporary r&b"], signals: { traits: ["sleek", "sensual"], colors: ["black", "burgundy", "gold", "white"], materials: ["rib knit", "satin", "mesh"], silhouettes: ["fitted", "body-skimming"], garmentTypes: ["rib knit long sleeve", "slip skirt", "silk cami", "gold hoops"], accessories: ["gold hoops", "compact shoulder bag"], aesthetics: ["polished", "sleek"] }, weight: 1 },
  { id: "alternative-rnb", genres: ["alternative r&b"], signals: { traits: ["moody", "artful"], colors: ["black", "plum", "silver", "smoky pink"], materials: ["mesh", "rib knit", "washed denim"], silhouettes: ["asymmetric", "body-skimming"], garmentTypes: ["layered tank", "slip skirt", "compact shoulder bag"], accessories: ["silver jewelry"], aesthetics: ["sleek", "offbeat"] }, weight: 0.9 },
  { id: "shoegaze-dream-pop", genres: ["shoegaze", "dream pop"], signals: { traits: ["hazy", "soft"], colors: ["lilac", "ice blue", "silver", "black"], materials: ["mesh", "washed denim", "fuzzy knit"], silhouettes: ["slouchy", "layered"], garmentTypes: ["slip dress", "cropped denim jacket", "sneakers"], accessories: ["silver jewelry"], aesthetics: ["ethereal", "blurred"] }, weight: 1 },
  { id: "dance-pop-electro", genres: ["dance pop", "electropop", "pop"], signals: { traits: ["glossy", "playful"], colors: ["hot pink", "acid green", "silver", "white"], materials: ["patent", "mesh", "metallic"], silhouettes: ["cropped", "fitted"], garmentTypes: ["mini skirt", "layered tank", "compact shoulder bag"], accessories: ["statement jewelry"], aesthetics: ["club", "digital"] }, weight: 1 },
  { id: "funk-disco-soul", genres: ["funk", "disco"], signals: { traits: ["groovy", "glossy"], colors: ["chocolate", "gold", "cream", "hot pink"], materials: ["satin", "suede", "metallic"], silhouettes: ["fitted", "flared"], garmentTypes: ["silk cami", "wide-leg trouser", "gold hoops"], accessories: ["gold jewelry"], aesthetics: ["retro", "polished"] }, weight: 0.85 },
  { id: "indie-general", genres: ["indie"], signals: { traits: ["offbeat", "casual"], colors: ["washed denim", "cream", "black", "smoky pink"], materials: ["washed denim", "cotton", "knit"], silhouettes: ["layered", "relaxed"], garmentTypes: ["cropped denim jacket", "graphic baby tee", "sneakers"], accessories: ["scarf"], aesthetics: ["artful", "worn-in"] }, weight: 0.8 },
  { id: "folk-blues", genres: ["folk", "blues"], signals: { traits: ["worn-in", "heritage"], colors: ["camel", "rust", "denim", "cream"], materials: ["suede", "denim", "cotton"], silhouettes: ["straight", "relaxed"], garmentTypes: ["wide-leg trouser", "clogs", "cropped denim jacket"], accessories: ["scarf"], aesthetics: ["handmade", "weathered"] }, weight: 1 },
  { id: "hip-hop-current", genres: ["hip-hop", "rap"], signals: { traits: ["confident", "bold"], colors: ["black", "white", "silver", "gold"], materials: ["denim", "leather", "cotton"], silhouettes: ["oversized", "low-slung"], garmentTypes: ["graphic baby tee", "wide-leg trouser", "sneakers", "compact shoulder bag"], accessories: ["gold jewelry"], aesthetics: ["street", "bold"] }, weight: 0.8 },
  { id: "hip-hop-90s", genres: ["hip-hop", "rap"], eras: ["1990s"], signals: { traits: ["confident"], colors: ["black", "denim", "gold", "white"], materials: ["denim", "leather", "cotton"], silhouettes: ["oversized", "low-slung"], garmentTypes: ["wide-leg trouser", "sneakers", "gold hoops"], accessories: ["gold jewelry"], aesthetics: ["street", "bold"] }, weight: 1 },
  { id: "lastfm-sensual", genres: ["sensual"], signals: { traits: ["sensual", "sleek"], colors: ["black", "burgundy", "plum"], materials: ["satin", "mesh", "rib knit"], silhouettes: ["fitted", "body-skimming"], garmentTypes: ["silk cami", "slip skirt", "rib knit long sleeve"], accessories: ["compact shoulder bag"], aesthetics: ["sensual", "polished"] }, weight: 0.75 },
  { id: "lastfm-romantic", genres: ["romantic"], signals: { traits: ["romantic", "soft"], colors: ["cream", "smoky pink", "burgundy"], materials: ["satin", "lace", "knit"], silhouettes: ["draped", "body-skimming"], garmentTypes: ["slip dress", "silk cami", "scarf"], accessories: ["gold jewelry"], aesthetics: ["romantic", "soft"] }, weight: 0.7 },
  { id: "lastfm-queer", genres: ["queer"], signals: { traits: ["expressive", "offbeat"], colors: ["hot pink", "black", "silver"], materials: ["mesh", "patent", "washed denim"], silhouettes: ["cropped", "asymmetric", "layered"], garmentTypes: ["graphic baby tee", "mini skirt", "compact shoulder bag"], accessories: ["statement jewelry"], aesthetics: ["playful", "offbeat"] }, weight: 0.7 },
  { id: "lastfm-feminist-riot", genres: ["feminist", "riot-grrrl"], signals: { traits: ["rebellious", "direct"], colors: ["black", "hot pink", "burgundy"], materials: ["distressed denim", "cotton", "leather"], silhouettes: ["structured", "slightly oversized"], garmentTypes: ["graphic baby tee", "moto jacket", "boots", "studded belt"], accessories: ["hardware"], aesthetics: ["rebellious", "distressed"] }, weight: 0.85 },
  { id: "lastfm-gothic", genres: ["gothic"], signals: { traits: ["moody", "dramatic"], colors: ["black", "plum", "silver"], materials: ["lace", "mesh", "leather"], silhouettes: ["body-skimming", "structured"], garmentTypes: ["slip dress", "boots", "moto jacket"], accessories: ["silver jewelry"], aesthetics: ["moody", "dramatic"] }, weight: 0.7 },
  { id: "lastfm-femme", genres: ["femme"], signals: { traits: ["expressive"], colors: ["smoky pink", "burgundy", "gold"], materials: ["satin", "mesh", "knit"], silhouettes: ["fitted", "draped"], garmentTypes: ["silk cami", "slip skirt", "gold hoops"], accessories: ["gold jewelry"], aesthetics: ["expressive", "polished"] }, weight: 0.55 },
  { id: "lastfm-dreamy-soft", genres: ["dreamy", "soft"], signals: { traits: ["dreamy", "soft"], colors: ["lilac", "ice blue", "smoky pink", "cream"], materials: ["fuzzy knit", "mesh", "satin"], silhouettes: ["draped", "layered"], garmentTypes: ["slip dress", "scarf", "cropped denim jacket"], accessories: ["silver jewelry"], aesthetics: ["ethereal", "soft"] }, weight: 0.72 },
  { id: "lastfm-experimental", genres: ["experimental"], signals: { traits: ["experimental", "offbeat"], colors: ["black", "silver", "hot pink"], materials: ["mesh", "patent", "metallic"], silhouettes: ["asymmetric", "structured"], garmentTypes: ["layered tank", "moto jacket", "compact shoulder bag"], accessories: ["statement jewelry"], aesthetics: ["artful", "offbeat"] }, weight: 0.78 },
  { id: "lastfm-club", genres: ["club"], signals: { traits: ["club", "glossy"], colors: ["black", "silver", "hot pink"], materials: ["patent", "mesh", "metallic"], silhouettes: ["fitted", "cropped"], garmentTypes: ["mini skirt", "layered tank", "boots"], accessories: ["statement jewelry"], aesthetics: ["club", "digital"] }, weight: 0.75 },
];
